[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (configure these in Netlify Dashboard)
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY

[build.environment]
  NODE_VERSION = "18"
